add_executable(HamtBench Bench.cpp)
target_link_libraries(HamtBench PRIVATE hamt immer_reference)
add_executable(SetBench SetBench.cpp)
target_link_libraries(SetBench PRIVATE hamt immer_reference)
add_executable(VectorBench VectorBench.cpp)
target_link_libraries(VectorBench PRIVATE vec immer_reference)
add_executable(FlexVectorBench FlexVectorBench.cpp)
target_link_libraries(FlexVectorBench PRIVATE vec immer_reference)
